modLoader="javafml"
loaderVersion="[47,)"
license="MIT"
issueTrackerURL="https://github.com/starforcraft/Creative-Wireless-Transmitter/issues/new/choose"
[[mods]]
modId="creativewirelesstransmitter"
version="${file.jarVersion}"
displayName="Creative Wireless Transmitter"
displayURL="https://www.curseforge.com/minecraft/mc-mods/creative-wireless-transmitter"
logoFile="logo.png"
credits="Thanks for downloading this mod."
authors="Ultramega"
description="This mod adds a Creative Wireless Transmitter."

[[dependencies.creativewirelesstransmitter]]
    modId="refinedstorage"
    mandatory=true
    versionRange="[1.12,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.creativewirelesstransmitter]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.creativewirelesstransmitter]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,)"
    ordering="NONE"
    side="BOTH"